[pytest]
testpaths = Customer Equipment-Management Invoice Vendor
python_files = test_*.py *_test.py cus02_to_cus24.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -v --ignore=Invoice/test_api.txt --ignore=Invoice/test_api_endpoints.py