[pytest]
testpaths = Customer Equipment-Management Invoice Vendor
python_files = cus02_to_cus24.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -v
norecursedirs = .git .venv videos __pycache__